github:
  token_env: GITHUB_TOKEN  # References environment variable

search:
  keywords: ["proxy", "bot", "keygen", "cracker", "scraper", "crawler", "vulnerability", "exploit"]
  languages: ["go", "rust", "python", "c"]
  max_repos_per_keyword: 50
  fork_instead_of_clone: true
  schedule: "0 */1 * * *"  # Every hour (cron format)

filter:
  max_inactive_months: 12
  min_stars_for_stale: 120

storage:
  local_dir: /home/gitbackup/github-mirror
  remote: my2tb:github-mirror
  offload_after_minutes: 5

discord:
  webhook_url_env: DISCORD_WEBHOOK_URL  # References environment variable
  enable_notifications: true
  batch_summary: true
  max_message_length: 1900

redis:
  address: "127.0.0.1:6379"
  password_env: REDIS_PASSWORD  # References environment variable
  db: 0

logging:
  level: "info"
  file: "/var/log/github-mirror-bot.log"
