github:
  token_env: GITHUB_TOKEN

search:
  keywords: ["proxy", "bot", "keygen", "cracker", "scraper", "crawler"]
  languages: ["go", "rust", "python", "c"]
  max_repos_per_keyword: 50
  fork_instead_of_clone: true
  schedule: "hourly"

filter:
  max_inactive_months: 12
  min_stars_for_stale: 120

storage:
  local_dir: /home/gitbackup/github-mirror
  remote: gdrive:github-mirror
  offload_after_minutes: 5
