github:
  token_env: "GH_TOKEN"

search:
  keywords:
    - query: "bot"
    - query: "scraper"
    - query: "proxy"
    - query: "keys"
    - query: "keygen"
    - query: "exploit"
    - query: "vulnerability"
    - query: "antivirus"
    - query: "cracked"
    - query: "cracker"
    - query: "crawler"
    - query: "scanner"
    - query: "bin"
    - query: "keys"
    - query: "topic:golang stars:>1000"
  languages: ["Go", "shell", "python", "C+", "typescript", "rust", ".sh"]
  max_repos_per_keyword: 5
  fork_instead_of_clone: false
  schedule: "0 */6 * * *"

filter:
  max_inactive_months: 12
  min_stars_for_stale: 100

storage:
  local_dir: "backups"
  remote: "my2tb:"
  offload_after_minutes: 60

discord:
  webhook_url_env: "DISCORD_WEBHOOK_URL"
  enable_notifications: true
  batch_summary: true
  max_message_length: 1800

redis:
  address: "localhost:6379"
  password_env: "REDIS_PASSWORD"
  db: 0

logging:
  level: "info"
  file: ""
