github:
  token_env: GITHUB_TOKEN

search:
  keywords: ["proxy", "bot", "keygen", "cracker", "scraper", "crawler", "vulnerability", "exploit"]
  languages: ["go", "rust", "python", "c"]
  max_repos_per_keyword: 50
  fork_instead_of_clone: true
  schedule: "0 */1 * * *"  # Every hour (cron format)

filter:
  max_inactive_months: 12
  min_stars_for_stale: 120

storage:
  local_dir: /home/gitbackup/github-mirror
  remote: my2tb:github-mirror
  offload_after_minutes: 5

discord:
  webhook_url: "https://discord.com/api/webhooks/XXXXXXXXX/XXXXXXXXXXXXXXXXXXXXXXXXXXXX"
  enable_notifications: true
  batch_summary: true  # Send summary of all repos found in one message
  max_message_length: 1900  # Discord limit is 2000, leave some buffer

redis:
  address: "127.0.0.1:6379"
  password: ""
  db: 0

logging:
  level: "info"
  file: "/var/log/github-mirror-bot.log"
