github:
  token: "${GITHUB_TOKEN}"
  user: "${GITHUB_USER}"
  min_stars: 50
  max_fork_age_days: 180
  languages: ["go", "python"]
  topics: ["bot", "automation"]
  search_interval: 3600 # seconds

discord:
  webhook_url: "${DISCORD_WEBHOOK_URL}"

backup:
  rclone_path: "/mnt/google-drive/github-backups"
  enabled: true
  sync_interval: 7200 # seconds

logging:
  level: "info"
  file: "bot.log"
